# Generated by Django 4.2.5 on 2023-11-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('businessman_userid', models.CharField(blank=True, max_length=255, null=True)),
                ('farmer_userid', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pending_businessmen_payment',
            },
        ),
    ]
