# Generated by Django 4.2.5 on 2023-11-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=30)),
                ('comment_content', models.TextField()),
                ('post_id', models.IntegerField()),
            ],
            options={
                'db_table': 'bloglist_comments',
            },
        ),
        migrations.CreateModel(
            name='React',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=30)),
                ('user_type', models.CharField(max_length=20)),
                ('post_title', models.CharField(max_length=255)),
                ('post_content', models.TextField()),
                ('post_uploaded', models.DateTimeField(auto_now_add=True)),
                ('post_image', models.TextField(blank=True, null=True)),
                ('comments', models.ManyToManyField(to='bloglist.comment')),
            ],
            options={
                'db_table': 'blog_list',
            },
        ),
    ]
