apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.22.2
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        resources:
          limits:
            cpu: "150m"   # 0.05 CPU cores
            memory: "150Mi"  # 64 megabytes
          requests:
            cpu: "100m"   # 0.025 CPU cores
            memory: "100Mi"  # 32 megabytes
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config-map
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
