# Generated by Django 4.2.5 on 2023-11-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(max_length=100)),
                ('max_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_bidder', models.CharField(blank=True, max_length=255, null=True)),
                ('bidding_ended', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'latest_bidding',
            },
        ),
    ]
