# Generated by Django 4.2.5 on 2023-12-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pending_farmer_payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='amount',
            new_name='price',
        ),
    ]
