# Generated by Django 4.2.5 on 2023-12-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='userid',
            field=models.CharField(max_length=100),
        ),
    ]
