# Generated by Django 4.2.5 on 2023-11-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_posts_datas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodinventory',
            table='auction_posts_inventory',
        ),
    ]
