# Generated by Django 4.2.5 on 2023-11-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_posts_datas', '0005_rename_foodinventory_auctionsinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionsinventory',
            old_name='items',
            new_name='description',
        ),
    ]
