# Generated by Django 4.2.5 on 2023-11-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_posts_datas', '0006_rename_items_auctionsinventory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionsinventory',
            name='posted_by',
            field=models.CharField(default='', max_length=255),
        ),
    ]
