# Generated by Django 4.2.5 on 2023-12-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=30)),
                ('businessman_userid', models.CharField(max_length=30)),
                ('review_content', models.CharField(max_length=250)),
                ('star', models.PositiveIntegerField(default=0)),
                ('product_id', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'farmer_review',
            },
        ),
    ]
