apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-list-permissions-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: monitoring
  # Replace "monitoring" with the correct namespace if needed
roleRef:
  kind: ClusterRole
  name: monitoring-list-permissions
  apiGroup: rbac.authorization.k8s.io
