apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-list-permissions
rules:
- apiGroups:
  - ""  # core API group
  resources:
  - pods
  - services
  - deployments
  # Add other resources as needed
  verbs:
  - list
