# Generated by Django 4.2.5 on 2023-11-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionsInventory',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_bidding_placed', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('current_time', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.CharField(default='', max_length=255)),
                ('description', models.TextField(max_length=555)),
            ],
            options={
                'db_table': 'incoming_auction_request',
            },
        ),
    ]
