apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- django-deployment.yaml
- django-service.yaml
- dev-test-role
- dev-test-role-binding
# Add overlays for Prometheus and Grafana
- overlays/prometheus
- overlays/grafana