apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mysql-deployment.yaml
- mysql-service.yaml
- phpmyadmin-deployment.yaml
- phpmyadmin-service.yaml
- django-deployment.yaml
- django-service.yaml
# Add overlays for Prometheus and Grafana
- overlays/prometheus
- overlays/grafana