# Generated by Django 4.2.5 on 2023-11-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('quality', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'bloglist_fooditems',
            },
        ),
        migrations.CreateModel(
            name='FoodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
                ('items', models.ManyToManyField(to='dataforfoods.fooditem')),
            ],
            options={
                'db_table': 'bloglist_inventory',
            },
        ),
    ]
