apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: dev-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:latest
        args:
          - -config.file=/etc/loki/local-config.yaml
          - -target=local
        volumeMounts:
          - name: loki-config
            mountPath: /etc/loki
      volumes:
      - name: loki-config
        configMap:
          name: loki-config
