name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set image tag
      id: set_tag
      run: echo "DOCKER_TAG=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV

    - name: Display directory contents
      run: ls -R

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_ID }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./backend/Dockerfile
        push: true
        tags: macorov/django_backend_bd_smart_agriculture:${{ env.DOCKER_TAG }}

    - name: Display contents of configfile directory
      run: ls -R configfile

    - name: Update Kubernetes deployment file
      run: |
        sed -i "s|macorov/django_backend_bd_smart_agriculture:latest|macorov/django_backend_bd_smart_agriculture:${{ env.DOCKER_TAG }}|g" configfile/django-deployment.yaml

    - name: Display contents of configfile directory after update
      run: ls -R configfile

    - name: Commit and push updated deployment file
      run: |
        cd configfile
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add django-deployment.yaml
        git commit -m "Update Docker image tag in deployment file"
        git push
